projectHandler/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('projects.urls')),
    path('account/',include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views
app_name = 'project'
urlpatterns = [
    path('',views.home,name='home'),
    path('create',views.create,name='create'),
    path('detail/<slug:slug>',views.detail,name='detail'),
    path('delete/<int:user_id>/<slug:slug>',views.delete,name='delete'),
    path('edit/<slug:slug>/<int:user_id>',views.edit,name='edit'),
    path('addcontribution/<int:project>/<int:user_id>',views.addcont.as_view(),name='addContribution')
   ]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('login',views.view_login,name='login'),
    path('register',views.view_register,name='register'),
    path('logout',views.view_logout,name='logout'),

]

templates/site/addcont.html
{% extends 'site/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
افزودن سازنده به پروژه
{% endblock  %}
{% block content %}
<form action="" method='post' autocomplete='off'>
{% csrf_token %}
<div class="col-md-12 mt-5">
{{form|crispy}}
<div class="col-md-1 mx-auto text-center mt-2"><input type="submit" value='افزودن' class='btn btn-block btn-outline-warning'></div>
</div>
</form>
{% endblock  %}

templates/site/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
<!-- JS, Popper.js, and jQuery -->
<script src="https://kit.fontawesome.com/c257c7be8a.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <title>مدیریت پروژه - {% block title %}
    {% endblock  %}</title>
</head>
<body>
<nav class="navbar navbar-light navbar-expand-md bg-warning giv-rtl">
  <a class="navbar-brand g" href="{% url 'project:home' %}">نرم افزار مدیریت پروژه</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link  btn btn-warning" href="{% url 'users:logout' %}">خروج<span class="sr-only">(current)</span></a>
      </li>
    {% else %}
      <li class="nav-item">
        <a class="nav-link btn btn-warning" href="{% url 'users:login' %}">ورود</a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-warning" href="{% url 'users:register' %}">ثبت نام</a>
      </li>
    {% endif %}  
    </ul>
  </div>
</nav>
{% block content %}
{% endblock  %}    
</body>
</html>

templates/site/create.html
{% extends 'site/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
ساخت پروژه
{% endblock  %}
{% block content %}
<form action="" method='post' autocomplete='off'>
{% csrf_token %}
<div class="col-md-12 mt-5">
<div class="col-md-6  mx-auto">{{form.name|as_crispy_field}}</div>
<div class="col-md-6  mx-auto">{{form.description|as_crispy_field}}</div>
<div class="col-md-1 mx-auto text-center mt-2"><input type="submit" value='ساختن' class='btn btn-block btn-outline-warning'></div>
</div>
</form>
{% endblock  %}

templates/site/delete.html
{% extends 'site/base.html' %}
{% block title %}
حذف پروژه
{% endblock  %}
{% block content %}
<h5 class='text-center mt-5'>آیا شما میخواهید این پروژه حذف کنید؟</h5>
<form method='post' autocomplete='off'>
{% csrf_token %}
<div class="col-md-1 text-center mx-auto mt-3"><input type="submit" value='حذف پروژه' class='btn btn-danger'></div> 
</form>
{% endblock  %}

templates/site/detail.html
{% extends 'site/base.html' %}
{% block title %}
  پروژه ی {{project.name|truncatewords:7}}
{% endblock  %}
{% block content %}
<table class="table table-hover text-center">
  <thead>
    <tr>
      <th scope="col">سازندگان</th>
      <th scope="col">دسترسی</th>
      <th scope="col">ساخته شده در</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{project.owner}}</td>
      <td class='badge badge-primary m-1'>Owner<i class="fas fa-crown"></i></td>
      <td>{{project.created}}</td>
    </tr>
  </tbody>
</table>
<div class="jumbotron jumbotron-fluid">
  <div class="container text-center">
    <h3>{{project.name}}</h3>
    <p class="lead giv-rtl">{{project.description}}</p>
    <a href="{% url 'project:addContribution' project.pk user.pk %}" class='btn btn-warning'>افزودن سازنده به پروژه</a>
  </div>
</div>
{% endblock  %}

templates/site/edit.html
{% extends 'site/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
ویرایش پروژه
{% endblock  %}
{% block content %}
<form action="" method='post' autocomplete='off'>
{% csrf_token %}
<div class="col-md-12 mt-5">
<div class="col-md-6  mx-auto">{{form.name|as_crispy_field}}</div>
<div class="col-md-6  mx-auto">{{form.description|as_crispy_field}}</div>
<div class="col-md-1 mx-auto text-center mt-2"><input type="submit" value='ویرایش' class='btn btn-block btn-outline-warning'></div>
</div>
</form>
{% endblock  %}

templates/site/index.html
{% extends 'site/base.html' %}

{% block title %}
صفحه اصلی
{% endblock  %}
{% block content %}
{% if user.is_authenticated %}
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h3>{{user.email}}</h3>
    <p class="lead giv-rtl">مهارت ها : {{user.talents}}</p>
  </div>
</div>
{% else %}
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h2 class='lead'>برای دیدن پروفایل باید وارد شوید یا ثبت نام کنید</h2>
    <h2 class='lead'>برای ساخت پروژه وارد شوید یا ثبت نام کنید</h2>
  </div>
</div>
{% endif %}
{% if user.is_authenticated %}
<div class="col-md-12 mx-auto text-center">
<div class="btn-group btn-group-toggle" data-toggle="buttons">
<a href="{% url 'project:create' %}" class='btn btn-warning'>ساخت پروژه</a>

</div>
</div>
{% endif %}
{% if user.is_authenticated %}
<div class='col-md-12 mt-5 mx-auto text-center'>
<div class="row d-flex justify-content-center">
{% for project in projects %}
<div class="card m-1 border border-primary" style="width: 18rem;">
  <div class="card-body p-5">
   <p class='badge badge-primary p-2'><span class='p-1'>Owner</span><i class="fas fa-crown"></i></p>
    <h5 class="card-title">{{project.name}}</h5>
    <p class="card-text">{{project.description|truncatewords:25}}</p>
    <a href="{% url 'project:detail' project.slug %}" class="btn btn-primary">مشاهده ی پروژه</a>
    <a href="{% url 'project:delete' user.pk project.slug %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
    <a href="{% url 'project:edit' project.slug user.pk %}" class="btn btn-success"><i class="fas fa-edit"></i></i></a>
  </div>
</div>
{% empty %}
<h3 class='mt-5 giv-rtl text-muted'>شما پروژه ای ندارید! یکی بسازید.</h3>
{% endfor %}
</div>
</div>
{% if pr %}
<div class='container-fluid text-center mt-3 p-5 bg-warning'><h3>پروژه هایی که شما در آن همکاری میکنید</h3></div>
{% for por in pr %}
<div class="card m-1 mt-5 border border-primary" style="width: 18rem;">
  <div class="card-body p-5">
   <p class='badge badge-primary p-2'><span class='p-1'>
{% if por.role == 'RD' %}
Developer
{% endif %}
   </span></p>
    <h5 class="card-title">{{por.project}}</h5>
  </div>
</div>


{% endfor %}
{% endif %}
{% endif %}
{% endblock  %}